### PR TITLE
Fix BGP regression

### LINKED ISSUE #269: [BUG]
# Bug Description
routeadvertisement latency defines multiple jobs with skip indexing set to true. 
However below code 
func (r *raLatency) Stop() error {
	var desiredCount uint64
	if r.JobConfig.SkipIndexing {Add commentMore actions
		return nil
	}
was removed in the PR https://github.com/kube-burner/kube-burner-ocp/pull/255 
Now kube-burnre-ocp is crashing while running the first job of the udn-bgp workload. Log of the first job output:

time="2025-06-25 08:12:06" level=info msg="Triggering job: udn-bgp-create-namespaces" file="job.go:108"
time="2025-06-25 08:12:06" level=info msg="0/2 iterations completed" file="create.go:118"
time="2025-06-25 08:12:06" level=debug msg="Creating object replicas from iteration 0" file="create.go:121"
time="2025-06-25 08:12:06" level=debug msg="Created namespace: udn-bgp-0" file="namespaces.go:55"
time="2025-06-25 08:12:06" level=debug msg="Creating object replicas from iteration 1" file="create.go:121"
time="2025-06-25 08:12:06" level=debug msg="Created namespace: udn-bgp-1" file="namespaces.go:55"
time="2025-06-25 08:12:06" level=debug msg="Created ConfigMap/udn-bgp-create-namespaces-1 in namespace udn-bgp-0" file="create.go:286"
time="2025-06-25 08:12:06" level=debug msg="Created ConfigMap/udn-bgp-create-namespaces-1 in namespace udn-bgp-1" file="create.go:286"
time="2025-06-25 08:12:06" level=info msg="Waiting up to 4h0m0s for actions to be completed" file="create.go:168"
time="2025-06-25 08:12:06" level=info msg="Actions in namespace udn-bgp-1 completed" file="waiters.go:73"
time="2025-06-25 08:12:06" level=info msg="Actions in namespace udn-bgp-0 completed" file="waiters.go:73"
time="2025-06-25 08:12:06" level=info msg="Verifying created objects" file="utils.go:119"
time="2025-06-25 08:12:06" level=debug msg="configmaps found: 2 Expected: 2" file="utils.go:157"
time="2025-06-25 08:12:06" level=info msg="Pausing for 30s before finishing job" file="job.go:167"
time="2025-06-25 08:12:36" level=info msg="Job udn-bgp-create-namespaces took 0s" file="job.go:175"
time="2025-06-25 08:12:36" level=info msg="Stopping measurement: raLatency" file="factory.go:149"
time="2025-06-25 08:12:46" level=debug msg="count 0 , desiredCount 0" file="routeadvertisement-latency_linux.go:733"
time="2025-06-25 08:12:46" level=debug msg="Desired count reached, signaling stop." file="routeadvertisement-latency_linux.go:735"
panic: close of nil channel

goroutine 101 [running]:
github.com/kube-burner/kube-burner-ocp/pkg/measurements.(*raLatency).Stop(0xc00044fb08)
        /home/ec2-user/kube-burner-ocp/pkg/measurements/routeadvertisement-latency_linux.go:756 +0x5c
github.com/kube-burner/kube-burner/pkg/measurements.(*Measurements).Stop(0x464c4c0?)
        /root/go/pkg/mod/github.com/kube-burner/kube-burner@v1.16.3/pkg/measurements/factory.go:150 +0x143
github.com/kube-burner/kube-burner/pkg/burner.Run.func1()
        /root/go/pkg/mod/github.com/kube-burner/kube-burner@v1.16.3/pkg/burner/job.go:179 +0x1787
created by github.com/kube-burner/kube-burner/pkg/burner.Run in goroutine 1
        /root/go/pkg/mod/github.com/kube-burner/kube-burner@v1.16.3/pkg/burner/job.go:89 +0x6d0
+ exit_code=2

### LINKED ISSUE #278: [BUG] BGP routeadvertisement latency metrics not working because of  refactoring in kube burner latency measurement
# Bug Description
This change https://github.com/kube-burner/kube-burner/pull/859 brought in lot of changes in measurements code. Measurement code in kube-burner-ocp is impacted by this refactoring.

### PR DESCRIPTION
**Pull request by venkataanil**
BGP workload is crashing as explained in the bug #269 So reverting back the needed change.

Fixes #269

RouteAdvertisement latency measurement code in kube-burner-ocp is
impacted by the kube-burner measurements refactoring PR https://github.com/kube-burner/kube-burner/pull/859 
To address this, kube burner PR #925, now exports some variables
which will be used in kube burner ocp to fix the regression.

Fixes #278

### CODE REVIEW

**Comment by venkataanil** [comment]
This PR has dependency on https://github.com/kube-burner/kube-burner/pull/925

File: pkg/measurements/routeadvertisement-latency_linux.go [hunk 1]
```diff
@@ -747,6 +744,9 @@ func (r *raLatency) waitForSceanrioCompletion(desiredCount uint64, maxTimeout ti
 // Stop stops raLatency measurement
 func (r *raLatency) Stop() error {
 	var err error
+	if r.JobConfig.SkipIndexing {
```
Comment (ygalblum) [inline pkg/measurements/routeadvertisement-latency_linux.go:747]: First, this doesn't seem related to this change.
Second, why is this handled here? Should it be handled in the caller? Also, Isn't this way to far in the process?

**Review by ygalblum — COMMENTED** [review]
This PR will also need to include an update to the `go.mod` file

**Comment by venkataanil** [comment]
> This PR will also need to include an update to the `go.mod` file

Agree, I will add the go.mod change when the relevant kube-burner PR merges and kube-burner release avaialble with that PR change.

**Comment by venkataanil** [comment]
ocp-e2e-ci Failures are not related to this change
```
`run_cmd ${KUBE_BURNER_OCP} virt-capacity-benchmark ${STORAGE_PARAMETER} --max-iterations 2  --data-volume-count 2 --vms 2 --skip-migration-job --skip-resize-job' failed due to timeout
`run_cmd ${KUBE_BURNER_OCP} virt-clone ${STORAGE_PARAMETER} --access-mode RWO --iterations 2 --iteration-clones 2' failed due to timeout
`run_cmd ${KUBE_BURNER_OCP} virt-ephemeral-restart ${STORAGE_PARAMETER} --access-mode RWO --iteration-vms 2 --iterations 2' failed due to timeout
```

**Comment by ygalblum** [comment]
@venkataanil yes, it was fixed in #301 and merged to main today. I rebased the PR on main. This should fix the CI

**Comment by venkataanil** [comment]
@ygalblum @vishnuchalla can you please review it again as CI is passing
